stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir -p public
    - rsync -av --exclude='public' . public/
  artifacts:
    paths:
      - public  # GitLab Pages serves files from the 'public' directory
  only:
    - main  # Only deploy from the main branch (adjust if needed)
